export const C = {
  bg: "#060c17",
  surface: "#0c1525",
  card: "#101c30",
  border: "#1a2e4a",
  accent: "#f97316",
  accentDim: "#7c2d12",
  blue: "#3b82f6",
  green: "#10b981",
  red: "#ef4444",
  purple: "#8b5cf6",
  pink: "#ec4899",
  text: "#e2e8f0",
  muted: "#475569",
  dim: "#334155",
};

export const STYLE = [
  "@import url('https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap');",
  "*, *::before, *::after { box-sizing: border-box; margin:0; padding:0; }",
  "body { font-family:'DM Sans',sans-serif; background:#060c17; color:#e2e8f0; }",
  "::-webkit-scrollbar{width:4px;height:4px}",
  "::-webkit-scrollbar-track{background:#0b1322}",
  "::-webkit-scrollbar-thumb{background:#1e3050;border-radius:4px}",
  "input,textarea,select{font-family:'DM Sans',sans-serif}",
  "button{cursor:pointer}",
  "/* Responsive Classes */",
  "@media (max-width: 768px) {",
  "  .grid-responsive { grid-template-columns: 1fr !important; }",
  "  .grid-responsive > * { min-width: 0; }",
  "  .flex-responsive { flex-direction: column !important; }",
  "  .hide-mobile { display: none !important; }",
  "  .show-mobile { display: block !important; }",
  "  .mobile-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); z-index: 1000; }",
  "  .mobile-sidebar { position: fixed !important; z-index: 1001 !important; height: 100vh; left: 0; top: 0; transform: translateX(0); transition: transform 0.3s; }",
  "  .mobile-sidebar.closed { transform: translateX(-100%); }",
  "  .table-responsive { overflow-x: auto !important; -webkit-overflow-scrolling: touch; width: 100%; }",
  "  .table-responsive table { min-width: 700px; }",
  "  .table-responsive th, .table-responsive td { white-space: nowrap; }",
  "  .p-mobile { padding: 16px !important; }",
  "  .gap-mobile { gap: 12px !important; }",
  "  .h-auto-mobile { height: auto !important; }",
  "  .flex-col-mobile { flex-direction: column !important; align-items: stretch !important; }",
  "  .flex-col-mobile > * { min-width: 0; }",
  "  .w-full-mobile { width: 100% !important; }",
  "}"
].join("\n");
