export const C = {
  bg: "#f0f2f5",
  surface: "#ffffff",
  card: "#ffffff",
  border: "#f0f0f0",
  accent: "#1677ff",
  accentDim: "#e6f4ff",
  blue: "#1677ff",
  green: "#52c41a",
  red: "#ff4d4f",
  purple: "#722ed1",
  pink: "#eb2f96",
  text: "#000000d9",
  muted: "#00000073",
  dim: "#00000040",
};

export const STYLE = [
  "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');",
  "*, *::before, *::after { box-sizing: border-box; margin:0; padding:0; }",
  "body { font-family:'Inter',sans-serif; background:#f0f2f5; color:#000000d9; }",
  "::-webkit-scrollbar{width:6px;height:6px}",
  "::-webkit-scrollbar-track{background:#f5f5f5}",
  "::-webkit-scrollbar-thumb{background:#bfbfbf;border-radius:4px}",
  "input,textarea,select{font-family:'Inter',sans-serif}",
  "button{cursor:pointer}",
  "/* Responsive Classes */",
  "@media (max-width: 768px) {",
  "  .grid-responsive { grid-template-columns: 1fr !important; }",
  "  .grid-responsive > * { min-width: 0; }",
  "  .flex-responsive { flex-direction: column !important; }",
  "  .hide-mobile { display: none !important; }",
  "  .show-mobile { display: block !important; }",
  "  .mobile-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); z-index: 1000; }",
  "  .mobile-sidebar { position: fixed !important; z-index: 1001 !important; height: 100vh; left: 0; top: 0; transform: translateX(0); transition: transform 0.3s; }",
  "  .mobile-sidebar.closed { transform: translateX(-100%); }",
  "  .table-responsive { overflow-x: auto !important; -webkit-overflow-scrolling: touch; width: 100%; }",
  "  .table-responsive table { min-width: 700px; }",
  "  .table-responsive th, .table-responsive td { white-space: nowrap; }",
  "  .p-mobile { padding: 16px !important; }",
  "  .gap-mobile { gap: 12px !important; }",
  "  .h-auto-mobile { height: auto !important; }",
  "  .flex-col-mobile { flex-direction: column !important; align-items: stretch !important; }",
  "  .flex-col-mobile > * { min-width: 0; }",
  "  .w-full-mobile { width: 100% !important; }",
  "}"
].join("\n");
