import React, { useState, useEffect } from 'react';
import { Bot, RefreshCw, FileText, CheckCircle, Calendar, Trash2, ChevronLeft, ChevronRight, Users, MessageSquare, Megaphone, IndianRupee } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { C } from '../constants/theme.js';
import { api } from '../services/api.js';

export const FounderReportsView = () => {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshTrigger, setRefreshTrigger] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [reportToDelete, setReportToDelete] = useState(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [snapshot, setSnapshot] = useState(null);

  const ITEMS_PER_PAGE = 10;
  const totalPages = Math.ceil(logs.length / ITEMS_PER_PAGE);
  const paginatedLogs = logs.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE);

  const confirmDelete = async () => {
    if (!reportToDelete) return;
    setIsDeleting(true);
    try {
      await api.deleteWorkflowLog(reportToDelete);
      toast.success("Report deleted");
      refreshLogs();
    } catch (err) {
      toast.error("Failed to delete report");
    } finally {
      setIsDeleting(false);
      setReportToDelete(null);
    }
  };

  useEffect(() => {
    const fetchLogs = async () => {
      setLoading(true);
      try {
        const [res, snapshotRes] = await Promise.all([
          api.getWorkflowLogs(),
          api.getFounderDashboard(),
        ]);
        // Filter only for WF06 - Founder Dashboard reports
        const founderReports = (res.logs || []).filter(log => log.workflow === 'WF06');
        setLogs(founderReports);
        setSnapshot(snapshotRes);
      } catch (err) {
        console.error('Failed to fetch founder reports', err);
        toast.error('Failed to load founder reports');
      } finally {
        setLoading(false);
      }
    };
    fetchLogs();
  }, [refreshTrigger]);

  const refreshLogs = () => {
    setRefreshTrigger(prev => prev + 1);
  };

  const renderFormattedMessage = (text) => {
    if (!text) return null;
    const lines = text.split('\n');
    let inList = false;
    const elements = [];
    let listItems = [];

    const flushList = () => {
      if (listItems.length > 0) {
        elements.push(<ul key={`ul-${elements.length}`} style={{ margin: '8px 0', paddingLeft: 24, paddingRight: 12 }}>{listItems}</ul>);
        listItems = [];
        inList = false;
      }
    };

    const parseInlineFormat = (lineStr) => {
      const parts = lineStr.split(/(\*\*.*?\*\*)/g);
      return parts.map((part, i) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return <strong key={i} style={{ color: C.text }}>{part.slice(2, -2)}</strong>;
        }
        return part;
      });
    };

    lines.forEach((line, idx) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('* ') || trimmed.startsWith('- ')) {
        inList = true;
        listItems.push(
          <li key={idx} style={{ marginBottom: 8, paddingLeft: 4 }}>
            {parseInlineFormat(line.replace(/^(\* |- )\s*/, ''))}
          </li>
        );
      } else {
        flushList();
        if (trimmed === '') {
          elements.push(<div key={`br-${idx}`} style={{ height: 8 }} />);
        } else {
          elements.push(
            <div key={`div-${idx}`} style={{ marginBottom: 4 }}>
              {parseInlineFormat(line)}
            </div>
          );
        }
      }
    });
    flushList();
    return elements;
  };

  return (
    <div style={{ padding: '32px', maxWidth: 1200, margin: '0 auto', fontFamily: "'Inter', sans-serif", maxHeight: 'calc(100vh - 80px)', overflowY: 'auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 32, fontWeight: 800, color: C.text, display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ padding: 10, background: 'rgba(99, 102, 241, 0.1)', borderRadius: 12, color: '#6366f1', display: 'flex' }}>
              <Bot size={24} />
            </div>
            AI Founder Reports
          </h1>
          <p style={{ margin: '8px 0 0 0', color: C.muted, fontSize: 15 }}>
            Automated daily executive summaries generated by your AI business analyst.
          </p>
        </div>

        <button
          onClick={refreshLogs}
          disabled={loading}
          style={{
            display: 'flex', alignItems: 'center', gap: 8, padding: '10px 18px',
            background: C.card, border: `1px solid ${C.border}`, borderRadius: 8,
            color: C.text, fontWeight: 600, cursor: loading ? 'not-allowed' : 'pointer',
            transition: 'all 0.2s', opacity: loading ? 0.7 : 1
          }}
        >
          <RefreshCw size={16} className={loading ? 'spin' : ''} />
          Refresh History
        </button>
      </div>

      {/* Reports Feed */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        {snapshot?.totals && (
          <div style={{ background: C.card, borderRadius: 16, border: `1px solid ${C.border}`, padding: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'center', marginBottom: 20, flexWrap: 'wrap' }}>
              <div>
                <h2 style={{ margin: 0, color: C.text, fontSize: 18 }}>All Brands Overview</h2>
                <p style={{ margin: '6px 0 0', color: C.muted, fontSize: 13 }}>{snapshot.totals.brands} configured brands · consolidated live data</p>
              </div>
              <span style={{ color: C.green, background: 'rgba(34,197,94,.1)', padding: '6px 10px', borderRadius: 20, fontSize: 12, fontWeight: 700 }}>ALL BRANDS</span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 12, marginBottom: 20 }}>
              {[
                [Users, 'Leads', snapshot.totals.leads],
                [Users, 'New Leads Today', snapshot.totals.leads_today],
                [Users, 'Hot Leads', snapshot.totals.hot_leads],
                [Calendar, 'Pending Follow-ups', snapshot.totals.followups_pending],
                [MessageSquare, 'Conversations', snapshot.totals.conversations],
                [MessageSquare, 'Conversations Today', snapshot.totals.conversations_today],
                [Megaphone, 'Campaigns', snapshot.totals.campaigns],
                [Megaphone, 'Active Campaigns', snapshot.totals.active_campaigns],
                [CheckCircle, 'Conversions', snapshot.totals.conversions],
                [CheckCircle, 'Conversion Rate', `${snapshot.totals.conversion_rate || 0}%`],
                [IndianRupee, 'Revenue', `₹${Number(snapshot.totals.revenue || 0).toLocaleString('en-IN')}`],
                [IndianRupee, 'Revenue Today', `₹${Number(snapshot.totals.revenue_today || 0).toLocaleString('en-IN')}`],
                [IndianRupee, 'Revenue This Month', `₹${Number(snapshot.totals.revenue_month || 0).toLocaleString('en-IN')}`],
              ].map(([Icon, label, value]) => (
                <div key={label} style={{ background: C.surface, border: `1px solid ${C.border}`, borderRadius: 12, padding: 16 }}>
                  <Icon size={16} color="#f97316" />
                  <div style={{ color: C.text, fontSize: 20, fontWeight: 800, marginTop: 10 }}>{value}</div>
                  <div style={{ color: C.muted, fontSize: 12, marginTop: 3 }}>{label}</div>
                </div>
              ))}
            </div>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 1800 }}>
                <thead><tr>{['Brand', 'Status', 'Leads', 'New Today', 'Hot', 'Follow-ups', 'Conversations', 'Conv. Today', 'Campaigns', 'Active Campaigns', 'Conversions', 'Conversion Rate', 'Revenue', 'Today Revenue', 'Month Revenue', 'Lead Sources'].map(label => <th key={label} style={{ textAlign: ['Brand', 'Status', 'Lead Sources'].includes(label) ? 'left' : 'right', padding: '10px 12px', color: C.muted, fontSize: 11, borderBottom: `1px solid ${C.border}`, whiteSpace: 'nowrap' }}>{label}</th>)}</tr></thead>
                <tbody>{snapshot.brands.map(brand => (
                  <tr key={brand.brand_id}>
                    <td style={{ padding: 12, color: C.text, fontWeight: 600, borderBottom: `1px solid ${C.border}` }}>{brand.brand}</td>
                    <td style={{ padding: 12, color: brand.brand_status === 'active' ? C.green : C.muted, borderBottom: `1px solid ${C.border}`, textTransform: 'capitalize' }}>{brand.brand_status || 'unknown'}</td>
                    {[
                      brand.leads, brand.leads_today, brand.hot_leads, brand.followups_pending,
                      brand.conversations, brand.conversations_today, brand.campaigns, brand.active_campaigns,
                      brand.conversions, `${brand.conversion_rate}%`,
                      `₹${Number(brand.revenue || 0).toLocaleString('en-IN')}`,
                      `₹${Number(brand.revenue_today || 0).toLocaleString('en-IN')}`,
                      `₹${Number(brand.revenue_month || 0).toLocaleString('en-IN')}`,
                    ].map((value, index) => <td key={index} style={{ padding: 12, color: C.text, textAlign: 'right', borderBottom: `1px solid ${C.border}`, whiteSpace: 'nowrap' }}>{value ?? 0}</td>)}
                    <td style={{ padding: 12, color: C.muted, borderBottom: `1px solid ${C.border}`, minWidth: 180 }}>
                      {brand.lead_sources?.length ? brand.lead_sources.map(source => `${source.source}: ${source.count}`).join(', ') : 'None: 0'}
                    </td>
                  </tr>
                ))}</tbody>
              </table>
            </div>
          </div>
        )}
        {loading && logs.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: C.muted, background: C.card, borderRadius: 16, border: `1px solid ${C.border}` }}>
            <RefreshCw size={24} className="spin" style={{ marginBottom: 12 }} />
            <p>Loading AI reports...</p>
          </div>
        ) : logs.length === 0 ? (
          <div style={{ padding: '60px 40px', textAlign: 'center', background: C.card, borderRadius: 16, border: `1px dashed ${C.border}` }}>
            <div style={{ width: 64, height: 64, borderRadius: 32, background: 'rgba(99, 102, 241, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 20px auto' }}>
              <FileText size={32} color="#6366f1" />
            </div>
            <h3 style={{ fontSize: 18, color: C.text, fontWeight: 700, margin: '0 0 8px 0' }}>No Reports Yet</h3>
            <p style={{ color: C.muted, maxWidth: 400, margin: '0 auto' }}>Run the Founder Dashboard workflow (WF06) in n8n to generate your first automated AI business report!</p>
          </div>
        ) : (
          <div style={{ background: C.card, borderRadius: 16, border: `1px solid ${C.border}`, overflow: 'hidden', boxShadow: '0 4px 20px rgba(0,0,0,0.2)' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ background: 'rgba(255,255,255,0.02)', borderBottom: `1px solid ${C.border}` }}>
                  <th style={{ padding: '16px 24px', color: C.muted, fontWeight: 600, fontSize: 13, width: '180px' }}>Date Generated</th>
                  <th style={{ padding: '16px 24px', color: C.muted, fontWeight: 600, fontSize: 13 }}>AI Executive Summary</th>
                  <th style={{ padding: '16px 24px', color: C.muted, fontWeight: 600, fontSize: 13, width: '150px' }}>Delivery Status</th>
                  <th style={{ padding: '16px 24px', width: '60px' }}></th>
                </tr>
              </thead>
              <tbody>
                {paginatedLogs.map((log) => (
                  <tr key={log.id} style={{ borderBottom: `1px solid ${C.border}`, transition: 'background 0.2s' }} className="hover-highlight">
                    <td style={{ padding: '24px', verticalAlign: 'top', color: C.text, fontSize: 14 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 500 }}>
                        <Calendar size={14} color={C.muted} />
                        {new Date(log.created_at).toLocaleString(undefined, {
                          month: 'short', day: 'numeric',
                          hour: 'numeric', minute: '2-digit'
                        })}
                      </div>
                    </td>
                    <td style={{ padding: '24px', verticalAlign: 'top', color: C.text, fontSize: 14, lineHeight: 1.6 }}>
                      <div style={{ opacity: 0.9 }}>{renderFormattedMessage(log.message)}</div>
                    </td>
                    <td style={{ padding: '24px', verticalAlign: 'top' }}>
                      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: C.green, fontSize: 12, fontWeight: 600, background: 'rgba(34,197,94,0.1)', padding: '6px 12px', borderRadius: 20 }}>
                        <CheckCircle size={14} /> Delivered
                      </div>
                    </td>
                    <td style={{ padding: '24px', verticalAlign: 'top', textAlign: 'right' }}>
                      <button onClick={() => setReportToDelete(log.id)} style={{ background: 'transparent', border: 'none', color: C.red, cursor: 'pointer', padding: 8, borderRadius: 6 }} className="hover-bg">
                        <Trash2 size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {totalPages > 1 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 24px', borderTop: `1px solid ${C.border}`, background: 'rgba(255,255,255,0.01)' }}>
                <span style={{ color: C.muted, fontSize: 13 }}>Showing {(currentPage - 1) * ITEMS_PER_PAGE + 1} to {Math.min(currentPage * ITEMS_PER_PAGE, logs.length)} of {logs.length} entries</span>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 32, height: 32, borderRadius: 6, background: C.surface, border: `1px solid ${C.border}`, color: C.text, cursor: currentPage === 1 ? 'not-allowed' : 'pointer', opacity: currentPage === 1 ? 0.5 : 1 }}>
                    <ChevronLeft size={16} />
                  </button>
                  <button onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 32, height: 32, borderRadius: 6, background: C.surface, border: `1px solid ${C.border}`, color: C.text, cursor: currentPage === totalPages ? 'not-allowed' : 'pointer', opacity: currentPage === totalPages ? 0.5 : 1 }}>
                    <ChevronRight size={16} />
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {reportToDelete && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)' }}>
          <div style={{ background: C.card, border: `1px solid ${C.border}`, borderRadius: 16, width: 400, padding: 32, boxShadow: '0 10px 40px rgba(0,0,0,0.3)' }}>
            <h3 style={{ margin: '0 0 16px 0', fontSize: 20, color: C.text, fontWeight: 700 }}>Delete Report</h3>
            <p style={{ margin: '0 0 32px 0', color: C.muted, fontSize: 14, lineHeight: 1.6 }}>Are you sure you want to permanently delete this founder report? This action cannot be undone.</p>
            <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end' }}>
              <button 
                onClick={() => setReportToDelete(null)}
                disabled={isDeleting}
                style={{ padding: '10px 20px', background: 'transparent', color: C.text, border: `1px solid ${C.border}`, borderRadius: 8, fontWeight: 600, cursor: isDeleting ? 'not-allowed' : 'pointer' }}
              >
                Cancel
              </button>
              <button 
                onClick={confirmDelete}
                disabled={isDeleting}
                style={{ padding: '10px 20px', background: C.red, color: 'white', border: 'none', borderRadius: 8, fontWeight: 600, cursor: isDeleting ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', gap: 8 }}
              >
                {isDeleting && <RefreshCw size={16} className="spin" />}
                Delete Report
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};
